apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-iot-ingress
  namespace: dev
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: hello-iot.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-iot-service
            port:
              number: 443
  tls:
  - hosts:
    - hello-iot.local
    secretName: hello-iot-tls
